### ISSUE TITLE
Conflict with the Experius/MultipleWebsiteStoreCodeUrl module

### ISSUE THREAD

**Issue by Alex7Lem** [alex-79/magento2-hide-default-store-code-from-url#1]
Приветствую Александр.
Спасибо за полезный модуль.

Расширение работает отлично, только есть один баг:
Magento ver. 2.3.5-p1
Ошибка происходит при переключении с любого Store View на default Store View.
Ошибка происходит только на homepage.

В строке браузера появляется ссылка:

> https://website.com/ru/stores/store/switch/?___from_store=ru&___store=en&uenc=aHR0cHM6Ly9tYXNrLmVjby8%2C

А на экране:

> 1 exception(s):
> Exception #0 (Exception): Notice: Undefined offset: 3 in /var/www/magento2/app/code/Experius/MultipleWebsiteStoreCodeUrl/Plugin/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrl.php on line 68
> 
> Exception #0 (Exception): Notice: Undefined offset: 3 in /var/www/magento2/app/code/Experius/MultipleWebsiteStoreCodeUrl/Plugin/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrl.php on line 68
> <pre>#1 Experius\MultipleWebsiteStoreCodeUrl\Plugin\Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl->beforeSwitch() called at [vendor/magento/framework/Interception/Interceptor.php:121]
> #2 Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #3 Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl\Interceptor->___callPlugins() called at [generated/code/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrl/Interceptor.php:26]

**Comment by Hexmage** [comment]
@Alex7Lem My Cyrillic is terrible. But the error message makes me think this module is directly conflicting with our Experius module, which are both different solutions for a similar problem.

**Comment by alex-79** [comment]
@Alex7Lem Согласен с @Hexmage, модули не совместимы. Думаю Вам прийдётся выбрать какой-то один из них.

**Comment by Alex7Lem** [comment]
> @Alex7Lem My Cyrillic is terrible. But the error message makes me think this module is directly conflicting with our Experius module, which are both different solutions for a similar problem.
Thanks for the help.
The error occurred due to a conflict with the Experius/MultipleWebsiteStoreCodeUrl module

**Comment by Alex7Lem** [comment]
> @Alex7Lem Согласен с @Hexmage, модули не совместимы. Думаю Вам прийдётся выбрать какой-то один из них.

**Comment by Alex7Lem** [comment]
> > @Alex7Lem Согласен с @Hexmage, модули не совместимы. Думаю Вам прийдётся выбрать какой-то один из них.

Спасибо за помощь.
Ошибка возникала из-за конфликта с модулем Experius/MultipleWebsiteStoreCodeUrl

**Comment by Alex7Lem** [comment]
> @Alex7Lem My Cyrillic is terrible. But the error message makes me think this module is directly conflicting with our Experius module, which are both different solutions for a similar problem.

Thanks for the help.
The error occurred due to a conflict with the Experius/MultipleWebsiteStoreCodeUrl module
