### ISSUE TITLE
Status code is 302 instead of 301

### ISSUE THREAD

**Issue by JelleGe** [alex-79/magento2-hide-default-store-code-from-url#10]
Hello,

The problem with this module, is that the redirect status code is 302 instead of 301.
That's bad for SEO.

Any idea how to change the statuscode from 302 to 301?

**Comment by alex-79** [comment]
Hello

Fixed to release [#1.0.5](https://github.com/alex-79/magento2-hide-default-store-code-from-url/releases/tag/1.0.5)

![Fixed to release 1.0.5](https://github.com/alex-79/magento2-hide-default-store-code-from-url/raw/master/doc/img/hide-default-store-code-from-url-magento-2-1-1.png)

**Comment by JelleGe** [comment]
Works perfect, thanks!
