### ISSUE TITLE
Duplicate links in Default Store View

### ISSUE THREAD

**Issue by Alex7Lem** [alex-79/magento2-hide-default-store-code-from-url#4]
Duplicate links remain in the Default Store View with the suffix Store Code https://mydomain.com/en/

The same page is displayed without the Store Code suffix https://mydomain.com/

Is it possible to get rid of duplicate links with the suffix https://mydomain.com/en/ ?

**Comment by petersafwat-flairs** [comment]
Same Problem here, any fixes?

**Comment by Alex7Lem** [comment]
Everything is still

**Comment by cptX** [comment]
Unfortunately this module is doing only half of the job. It should also take care of the redirect but is not!
So I had to create redirect in my nginx configuration.

**Comment by alex-79** [comment]
Fixed to release [ #1.0.2 ](https://github.com/alex-79/magento2-hide-default-store-code-from-url/releases/tag/1.0.2)

**Comment by cptX** [comment]
Hi @alex-79,
thanks for your quick reaction. In between I had implemented the redirect in my nginx. So I wanted to ask you, by implementing the redirect in your module do we have any performance issues compared with the redirect in nginx? I understand that your redirect happens in php, but if we think that actually the redirect would be needed in rare occassions logically this will not be an issue. For example redirect could happen if somebody manually adds the language suffix in the url. The spider robots should never arrive on the language suffix url so I think by implementing it in the module and not in nginx will not be an issue. What is your opinion in the subject?

**Comment by cptX** [comment]
By trying to update I got this error

$ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires noon/hide-default-store-code dev-master -> satisfiable by noon/hide-default-store-code[dev-master].
    - noon/hide-default-store-code dev-master requires magento/module-store ^102.0|^103.0 -> found magento/module-store[100.0.2, ..., 100.2.10, 101.0.0, ..., 101.1.5] but it does not match the constraint.
    
Can you please explain what is wrong here and what to do?

**Comment by alex-79** [comment]
Fixed to release [#1.0.3](https://github.com/alex-79/magento2-hide-default-store-code-from-url/releases/tag/1.0.3)

**Comment by cptX** [comment]
Hi, I have tested 1.0.3 and it worked correctly!
@alex-79 can you please give me a feedback about my concern about performance I have written in a previous comment?
Could this redirect functionality have performace issues compared to nginx implementation?
