### ISSUE TITLE
Can't remove after delete from app/code/

### ISSUE THREAD

**Issue by kaanair** [alex-79/magento2-hide-default-store-code-from-url#7]
I deleted Noon/HideDefaultStoreCode folder from as you provided path and still in database or somewhere .
So for this reason I can't use any command in SSH and return "not found Noon/HideDefaultStoreCode "
Do you know where is the table in database ?

**Comment by alex-79** [comment]
My module does not create new tables. You can run the command: php bin/magento setup:upgrade
