### ISSUE TITLE
Not installing the latest version

### ISSUE THREAD

**Issue by cptX** [alex-79/magento2-hide-default-store-code-from-url#9]
Sorry if it is my mistake, but by running the command
`composer require noon/hide-default-store-code`
the version 1.0.1 was installed and not the 1.0.3.

Did I do something wrong or is something wrong in your side?
What do you suggest? I need the last version because I need the redirect.

If I ran
`composer require noon/hide-default-store-code`

I get
`Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.0 for noon/hide-default-store-code
./composer.json has been updated
Running composer update noon/hide-default-store-code
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  Locking noon/hide-default-store-code (1.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  Installing noon/hide-default-store-code (1.0.1): Extracting archive
`

Also if I run

`composer require noon/hide-default-store-code 1.0.3`

I get:

`./composer.json has been updated
Running composer update noon/hide-default-store-code
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires noon/hide-default-store-code 1.0.3 -> satisfiable by noon/hide-default-store-code[1.0.3].
    - noon/hide-default-store-code 1.0.3 requires magento/magento-composer-installer ~0.3.0 -> found magento/magento-composer-installer[0.3.0] but the package is fixed to 0.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

I suspect that the problem is this line in composer.json in your module.

"magento/magento-composer-installer": "~0.3.0"

I don't have a good knowledge here but shouldn't it be ">=0.3.0"?
Please advise!

**Comment by alex-79** [comment]
Fixed to release [#1.0.4](https://github.com/alex-79/magento2-hide-default-store-code-from-url/releases/tag/1.0.4)

**Comment by cptX** [comment]
Checked and now is fine! Thanks!
